<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-AFQPLSSL" failures="1" tests="2" name="Error validation Test" time="12.788" errors="0" timestamp="2024-09-01T18:29:15 IST">
  <testcase classname="Practice.saucedemo.tests.ErrorValidation" name="Productvalidation" time="1.13"/>
  <testcase classname="Practice.saucedemo.tests.ErrorValidation" name="StandaloneTest" time="0.618">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not match any user in this service] but found [ Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this service] but found [ Username and password do not match any user in this service]
at Practice.saucedemo.tests.ErrorValidation.StandaloneTest(ErrorValidation.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- StandaloneTest -->
</testsuite> <!-- Error validation Test -->
