<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-AFQPLSSL" failures="1" tests="3" name="Error validation Test" time="28.187" errors="0" timestamp="2024-10-26T12:48:11 IST">
  <testcase classname="Practice.saucedemo.tests.ErrorValidation" name="Productvalidation" time="1.792"/>
  <testcase classname="Practice.saucedemo.tests.ErrorValidation" name="StandaloneTest" time="0.448">
    <skipped/>
  </testcase> <!-- StandaloneTest -->
  <testcase classname="Practice.saucedemo.tests.ErrorValidation" name="StandaloneTest" time="0.401">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not match any user in this service] but found [ Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this service] but found [ Username and password do not match any user in this service]
at Practice.saucedemo.tests.ErrorValidation.StandaloneTest(ErrorValidation.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- StandaloneTest -->
</testsuite> <!-- Error validation Test -->
